### ISSUE TITLE
Make generating models directory optional

### ISSUE THREAD

**Issue by apgapg** [hiranthaR/Json-to-Dart-Model#15]
When we go into creating different modules in project, everytime I need to delete the extraneous `models` folder and move the inner files into outer parent.
Not everytime one needs to generate models dir. Hence can we have a optional dialog asking to generate models dir?

**Comment by iamarnas** [comment]
Hi, 
 In your situation you should navigate to models map. if not exist create it.
```
/lib -> /models
```
After when generating is complete. Your map structure should look like this.
```
/lib -> /models -> /models
```
Last map keeps all your generated files in one place and completely separate. Your need just rename it to the base `class` name. Here's how my map structure looks like.

![Skärmavbild 2021-02-04 kl  09 53 08](https://user-images.githubusercontent.com/42679871/106868244-d3f0c580-66ce-11eb-9db2-03aa4a6635c0.png)

This structure allow your easy find and delete files. `models.dart` is dart barrel file which keep all exports of the base `class`.

 Of course, it is possible to rename the `models` map with the users' base class name. But I think it is better to keep the same name, it makes possible to find faster and easier generated files in the long list for the next processes.

Like you see in my case I see it with the red color :D

**Comment by apgapg** [comment]
I agree with what you said. Keeping all models in one folder is standard practice. But in my case, each module contains its own model's dir with child being folder for grouping different models.
No worries, one can do manually moving of files after generation. Also, it's a one-time process so no hurt in doing that.

Thanks for the quick reply @iamarnas

**Comment by iamarnas** [comment]
@apgapg Hi,
I have added a new feature to the `Json to Dart Model` generator. Now your can build your modules from the single file. It give you more flexibility and you can configure generator how your want. Maybe you will find answer in this quastion. [Read the documentation.](https://github.com/hiranthaR/Json-to-Dart-Model/blob/master/README.md#convert-from-file)

**Comment by apgapg** [comment]
@iamarnas This is a cool addition. Having a config file helps to maintain a hardcoded configuration. This will definitely help im future json model managing.

**Comment by Miamoto-Musashi** [comment]
would be definitely very useful to have this option for 2 reasons:

1- it is annoying to have to move all generated models from inner directories, if I use other transformations on the models after generation I would like them to be in one single folder
2- there is the option that the inner folders contains same generated object referenced twice on the json

do you think we can reopen this request and handle it?

thanks

best

**Comment by iamarnas** [comment]
> would be definitely very useful to have this option for 2 reasons:
> 
> 1- it is annoying to have to move all generated models from inner directories, if I use other transformations on the models after generation I would like them to be in one single folder
> 2- there is the option that the inner folders contains same generated classes referenced twice in the json
> 
> do you think we can reopen this request and handle it?
> 
> thanks
> 
> best

@Miamoto-Musashi Hi 👋

This generator separates classes to different files and `models` folder, does not allow to mix them with others files in the same folder. You just need to rename it however you want. 
 Men this will be improved with the next release. It will be possible to select the directory from the right mouse button context 😉

**Comment by iamarnas** [comment]
@Miamoto-Musashi Hi,

 Can you test the new [features](https://github.com/iamarnas/Json-to-Dart-Model#context-actions) now and look if match your preferences. Would be nice to hear your opinion if it is possible to improve something more when it comes to easily run the conversion.

**Comment by Miamoto-Musashi** [comment]
Sure, you don't have to mix the files it's enough to replace with the last one, if the genereted contains errors we notice by compilation issue

**Comment by Miamoto-Musashi** [comment]
> @Miamoto-Musashi Hi,
> 
> Can you test the new features [actions from the context](https://github.com/hiranthaR/Json-to-Dart-Model#context-actions) and look if match your preferences. Would be nice to hear your opinion if it is possible to improve something more when it comes to easily run the conversion.

the context generation works well ;)
