### ISSUE TITLE
plural class name

### ISSUE THREAD

**Issue by Miamoto-Musashi** [hiranthaR/Json-to-Dart-Model#44]
**Describe the bug**
models from array struct are generated in plural forms

**To Reproduce**
given the json

```json
{
    "__className": "Document",
    "title": "INSURANCE",
    "ownerOrganizationKey": "778a69f7-d98c-4464-859c-f700c7a33162",
    "status": "approved",
    "pages": [
      {
        "key": "5621f8a9-f05a-4469-bddf-0cdb56b24771-3",
        "image": null,
        "local_uri": "/var/mobile/Containers/Data/Application/2D3D40E2-4DBD-4364-A9D5-3F50732A63A0/Documents/camera/pictures/CAP_8C794E18-11AE-43CE-B8A8-B8395ED1F06A.jpg",
        "documentTitle": "INSURANCE",
        "documentKey": "5621f8a9-f05a-4469-bddf-0cdb56b24771"
      }
]
}
```

and using json generation the model generated is 

```dart
class Pages{
....
}
```

**Expected behavior**
Class name should be `Page`

**Screenshots**

**Version**
3.2.5

**Json**
see above

**Additional context**
using Jsonc file generation

**Comment by iamarnas** [comment]
@Miamoto-Musashi Hi.

I would not say that it's a bug. In this case `JSON` key `pages` for list object used for value name for type names as `List<Pages>` and for unnamed list object inside the `pages` list. It possible to remove `s` letter but I don't know if not defect names and I'm not sure if all plural have `s` at the end? Need to test.

**Comment by Miamoto-Musashi** [comment]
yes Is in the middle from a bug and an enhancement, let's say the expected behavior is to have List<Page> objects in the array not Pages, probably a simple implementation can start removing s at the end but then you need to consider noun like man/men, child/children and so on.

Probably introducing references between objects (see task #45 ) can solve both

Best

**Comment by iamarnas** [comment]
@Miamoto-Musashi I have consulted with a friend who speaks English. And he said that it would work 99% to remove only `s` at the end for the rest 1% he not garante 😁
 I will fix it as soon as possible.

**Comment by Ascenio** [comment]
Just would like to add that there's some cases where trimming `s` isn't enought. Imagine `countries` for example, it should be changed to `country`, but then there might be i18n issues because I'm not sure if it's always enough to replace `ies` with `y`.

**Comment by iamarnas** [comment]
> Just would like to add that there's some cases where trimming `s` isn't enough. Imagine `countries` for example, it should be changed to `country`, but then there might be i18n issues because I'm not sure if replacing `ies` by `y` always solves the problem.

@Ascenio Thanks for the correction. You are right.
