### ISSUE TITLE
[BUG] Duplicate models generated

### ISSUE THREAD

**Issue by Prn-Ice** [hiranthaR/Json-to-Dart-Model#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have the following models declared in my `models.jsonc`

```json
{
		"__className": "create_wallet_address_response",
		"__path": "/lib/app/modules/deposit_withdraw/data/models/create_wallet_address_response",
		"status": "success",
		"data.walletAddress": {
			"id": "4e252595-d326-4c26-89cc-f23d001ffa4a",
			"account_id": "348e961f-899f-4790-b8e8-712616b74614",
			"address": "1Msn2kMzveVCgX7i1ZpJWHGnEmNP7LBBL1",
			"coin": "BTC"
		}
	},
{
		"__className": "wallet_addresses_response",
		"__path": "/lib/app/modules/deposit_withdraw/data/models/wallet_addresses_response",
		"status": "success",
		"data.walletAddress": [
			{
				"id": "4e252595-d326-4c26-89cc-f23d001ffa4a",
				"account_id": "348e961f-899f-4790-b8e8-712616b74614",
				"address": "1Msn2kMzveVCgX7i1ZpJWHGnEmNP7LBBL1",
				"coin": "BTC"
			}
		]
	}
```

After building models, the `data.walletAddress` class is generated twice, even though its the exact same model.

### Expected Behavior

Since the same model is declared twice, build only the first and reference it in the other.

### Version

```markdown
3.3.9
```

**Comment by iamarnas** [comment]
@Prn-Ice Hi 👋 
By changing the path to the same object you tell to the generator that you want the same object in the different place.
In your case, your `jsonc` should look like that:
```jsonc
{
        "__className": "create_wallet_address_response",
        "__path": "/lib/app/modules/deposit_withdraw/data/models/wallet_address_response",
        "status": "success",
        "data.walletAddress": {
            "id": "4e252595-d326-4c26-89cc-f23d001ffa4a",
            "account_id": "348e961f-899f-4790-b8e8-712616b74614",
            "address": "1Msn2kMzveVCgX7i1ZpJWHGnEmNP7LBBL1",
            "coin": "BTC"
        }
    },
    {
        "__className": "wallet_addresses_response",
        "__path": "/lib/app/modules/deposit_withdraw/data/models/wallet_address_response",
        "status": "success",
        "data.walletAddress": [
            {
                "id": "4e252595-d326-4c26-89cc-f23d001ffa4a",
                "account_id": "348e961f-899f-4790-b8e8-712616b74614",
                "address": "1Msn2kMzveVCgX7i1ZpJWHGnEmNP7LBBL1",
                "coin": "BTC"
            }
        ]
    }
```
You are welcome to describe more your opinion if I not understood you right.

**Comment by iamarnas** [comment]
@Prn-Ice I need
I see you work a lot with the `jsonc` file and I need your opinion. What do you think if I move the path to the options object?
#### The `JSON` object options should look like this:
```jsonc
"__options": {
    "codeGenerator": "Default", // ['Default', 'JSON', 'Freezed']
    "immutable": false,
    "toString": "Default", // ['Default', 'Auto', 'Stringify', 'Dart']
    "copyWith": false,
    "equality": "Default", // ['Default', 'Equatable', 'Dart']
    "targetDirectory": "/lib/src/models", // <- override path here
    "runBuilder": false,
    "sortConstructorsFirst": false,
    "includeIfNull": false
},
```
Then you can use it in this way:
```json
{
    "__className": "user",
    "__options": {
        "toString": "Dart", 
        "equality": "Dart", 
        "targetDirectory": "/lib/src/models"
    },
    "name": "Name",
    "id": 1010
}
```
This setup would allow configuring different output options for every JSON object.

**Comment by Prn-Ice** [comment]
@iamarnas  Looks good.

**Comment by Prn-Ice** [comment]
@iamarnas thanks, your solution worked, I'll leave the issue open while we wait for @Miamoto-Mushashi to respond.

**Comment by Miamoto-Musashi** [comment]
Hi @Prn-Ice and @iamarnas,
in my experience you can have two patterns: all models in one folder than the setting should be global, one model for every module or feature implemented (like in clean architecture patterns) in this case every object have his path.
Best option should be to have a global setting overwritten, just in case, in the jsonc file

**Comment by iamarnas** [comment]
@Miamoto-Musashi It should be two patterns. First if you not put options to the json object the default options automatically will read from settings. Second you can override by adding options to the object. User can decide how to owerride.

**Comment by iamarnas** [comment]
@Miamoto-Musashi I think if user have possibility create path to every module his can build clean architecture patterns self.

**Comment by iamarnas** [comment]
I made another issue that originates from this issue.
Since this particular one is finished I will close the issue.

Thank you for your recommendations:
@Miamoto-Musashi 
@Prn-Ice
