### ISSUE TITLE
Generate JSON from the multi files

### ISSUE THREAD

**Issue by iamarnas** [hiranthaR/Json-to-Dart-Model#68]
Add the ability to generate JSON from multiple files.

Thanks for idea to @Prn-Ice

**Comment by iamarnas** [comment]
@Prn-Ice Hi 👋
I work now with JSON from multiple files. And my setup now is:
Generator read files from the expected map directory `json_models`. Supported files are `*.json` and `*.jsonc`. Inside the files can be a single JSON object or list with JSON objects, just required to add a class name for every object like always. 

Do you have any suggestions with your experience?

**Comment by iamarnas** [comment]
@Prn-Ice Hi 👋

You wanted multiple json file support and now it available in the latest version. Can you test it when you have time and or it's what you expected?

**Comment by iamarnas** [comment]
Closing it due to #65

**Comment by Prn-Ice** [comment]
@iamarnas, very sorry for the delayed response, I haven't used the extension in a while because I had to switch focus to an older project that needed a lot of work.

I'll be testing and reporting my experience in the coming days, thank you so much for adding it.

**Comment by iamarnas** [comment]
@Prn-Ice No problem at all it's not big deal 😉 Hope you will like news features.
