### ISSUE TITLE
[BUG] Not creating models

### ISSUE THREAD

**Issue by 01FC** [hiranthaR/Json-to-Dart-Model#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to create models from clipboard

Ctrl+shift+p (open command pallete)
search for JSON to Dart from clipboard
enter the required data (classes name, etc)

And nothing happens

### Expected Behavior

Trying to create models from clipboard

Ctrl+shift+p (open command pallete)
search for JSON to Dart from clipboard
enter the required data (classes name, etc)

The models are created in the folder. (like it used to be before)

### Steps To Reproduce

Ctrl+shift+p (open command pallete)
search for JSON to Dart from clipboard
enter the required data (classes name, etc)

### Version

```markdown
3.5.1
```

### Relevant JSON syntax

```shell
{
"user":"usuario",
"number":"123",
"others":{"color":"yes","enabled":true}
}
```

**Comment by iamarnas** [comment]
@01FC Hi 👋

Thank you for your report. This is a known problem for windows and I hope I have fixed this in the latest version, but am waiting for @hiranthaR when he will update it. For now you can [convert from the file](https://github.com/hiranthar/Json-to-Dart-Model#convert-from-file) until new release.

**Comment by 01FC** [comment]
downgraded to 3.41 until the issue is fixed. Thanks

**Comment by iamarnas** [comment]
@01FC Hi 👋

Can you test latest 3.5.3 version to see if no issues?
