### ISSUE TITLE
number cast to int not double

### ISSUE THREAD

**Issue by jinjilynn** [hiranthaR/Json-to-Dart-Model#78]
```json
{
     "totalManPrice": 0.0,
}
```

for example, i have a json snippet, and when i use command 'From Clipboard to Code Generation Classes', I get the result of 

```dart
   totalManHour: json['totalManHour'] as int?,
```
is there some config to default num type as double?

**Comment by iamarnas** [comment]
@jinjilynn Hi 👋 Thank you for reporting. 

This is known issue becouse 0.0 is equal to 0 and TypeScript read it as double and integer. Generator just prefer integer in this situation. To get double you need just correct to double as in the example below 👇

```json
{
     "totalManPrice": 0.1,
}
```
I will try to fix it when I I'll have free time.

**Comment by jinjilynn** [comment]
> @jinjilynn Hi 👋 Thank you for reporting.
> 
> This is known issue becouse 0.0 is equal to 0 and TypeScript read it as double and integer. Generator just prefer integer in this situation. To get double you need just correct to double as in the example below 👇
> 
> ```json
> {
>      "totalManPrice": 0.1
> }
> ```
> 
> I will try to fix it when I I'll have free time.

ok,thank you
