### ISSUE TITLE
[BUG] <Command failed: cscript /Nologo c:\Users\\.vscode\extensions\hirantha.json-to-dart-3.5.0\node_modul>

### ISSUE THREAD

**Issue by anilghimire133** [hiranthaR/Json-to-Dart-Model#79]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Generate JSON to dart class from JSON file.

### Version

```markdown
v3.5.3
```

### Relevant JSON syntax

```shell
{
    "status": 200,
    "message": "Profile Updated Successfully.",
    "response": {
        "help_intro": 1
    }
}
```

**Comment by anilghimire133** [comment]
![image](https://user-images.githubusercontent.com/22236736/143467585-ba038dc4-ace1-4352-8bf6-c8a97e18f667.png)

**Comment by anilghimire133** [comment]
When I copied the JSON file and generated the model JSON to dart. It just create a folder for class and couldn't create a class for JSON to dart? I am using windows 10.

**Comment by iamarnas** [comment]
@anilghimire133 Hi 👋 

This error comes from `copy-paste` dependency. I have updated to the latest version. You can update to the latest version of the extension and try if still throws an error.

**Comment by anilghimire133** [comment]
![image](https://user-images.githubusercontent.com/22236736/143683061-ea41a349-aa7e-458b-aac5-6380257b66e5.png)
I Updated to the latest version. The same error comes.

**Comment by iamarnas** [comment]
@anilghimire133 Hi

Can you test the latest version `3.5.5`? For me, it works without problems on Windows 10 :)

**Comment by anilghimire133** [comment]
hi, @iamarnas Thank you so much it worked.
![image](https://user-images.githubusercontent.com/22236736/143898379-62693082-8ee9-47ca-9050-095b0872f479.png)
