### ISSUE TITLE
Effective Dart style.

### ISSUE THREAD

**Issue by iamarnas** [hiranthaR/Json-to-Dart-Model#8]
**Describe the bug**
Would it be possible follow effective dart style guides.

**Screenshots**
![Skärmavbild 2020-12-22 kl  14 26 53](https://user-images.githubusercontent.com/42679871/102893922-9871a300-4462-11eb-8ca2-1d19e0edb752.png)

**Version**
version: 2.4.1

**Comment by hiranthaR** [comment]
I'll try to manage my time for this. thank you for the suggestion

**Comment by iamarnas** [comment]
@hiranthaR Hi again.

I found one bug to. Most of API providers use word `get` in their json files you can see in my bild example. And when your extension generate code his create `String value` with name `get` which is reserved by system. I recommend to regenerate this to example: `class Products {}` generate `String getProtucts` instead `String get`.
![Screenshot_20201222_151709_org.mozilla.firefox.png](https://user-images.githubusercontent.com/42679871/102899719-a37d0100-446b-11eb-80f0-94196c24e91e.png)

**Comment by iamarnas** [comment]
@hiranthaR  Hi, 
 I have updated your app syntax.ts file and you can see how was before and after update.

### Before:
![Skärmavbild 2020-12-27 kl  17 47 30](https://user-images.githubusercontent.com/42679871/103175707-410d7180-486c-11eb-979e-2d76c0d19965.png)
### After:
![Skärmavbild 2020-12-27 kl  17 43 51](https://user-images.githubusercontent.com/42679871/103175710-44086200-486c-11eb-91b8-6d0f8c0b6b58.png)

And now all generated files by your extension is full supported [Effective Dart: Style](https://dart.dev/guides/language/effective-dart/style) and friendly with expert developers :)

No more `List<Null>`warning and all reserved values by syntax are regenerated automatically. You can see in the example what it looks like.
Planning add automatic identification of `DateTime` and `copyWith();`

**Comment by iamarnas** [comment]
Today added `copyWith();` method. User can choose before generating files :)

![Skärmavbild 2020-12-27 kl  19 32 35](https://user-images.githubusercontent.com/42679871/103177441-d879c100-487a-11eb-8c8d-88ca27543d2b.png)

**Comment by hiranthaR** [comment]
@iamarnas hi, I fixed others without copyWith function. I'll do it another day. can you check your requirements are satisfied?

**Comment by iamarnas** [comment]
@hiranthaR Nice, I'll do it.  I did not expect you to fix it so quickly.  That's why I updated your extension it myself :) If you are interested I can share to you my changes. I have advanced syntax formatting it detect when needs expression function or block function very correct to [dartfmt](https://dart.dev/tools/dartfmt).  And planning to add for to ask user if he want use immutable classes or not. Because for now only with Equatable creates immutable classes. It should be more flexible.

**Comment by hiranthaR** [comment]
@iamarnas oh sorry. I didn't know that. sure open a PR. I'll revert my commits and publish yours. It's totally fine.

**Comment by iamarnas** [comment]
@hiranthaR  Hi,
Here is your result after new update :)

![Skärmavbild 2020-12-28 kl  23 57 26](https://user-images.githubusercontent.com/42679871/103248010-456b8480-4969-11eb-8b12-70dc1939439e.png)

remove `const` from the constructor for now. It's not immutable class and it will show lint error for all created classes. That why I want add function to ask users if they want use `@immutable` classes. Leave me to fix all Dart languages guide lines becouse im pedantic Dart user ;)

**Comment by hiranthaR** [comment]
I think we are better to go with your changes

**Comment by iamarnas** [comment]
@hiranthaR  Hi. Opened a PR. Just needs update the readme-file after new changes. And here your English is better than mine :)

**Comment by iamarnas** [comment]
How it looks syntax after update.
![carbon(1)](https://user-images.githubusercontent.com/42679871/103279706-b09b7200-49ce-11eb-9f60-9394bb566f91.png)
![carbon](https://user-images.githubusercontent.com/42679871/103279710-b42ef900-49ce-11eb-9948-d5273f5753aa.png)
