### ISSUE TITLE
It is not generating a dart model from models.jsonc file

### ISSUE THREAD

**Issue by iqboladahamjonov** [hiranthaR/Json-to-Dart-Model#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to build a dart model based on models.jsonc file from directory ztest, it unfortunately it won't build the file neither with hotkey ctrl + shift + alt + B, nor with command pallete build command. the error says "Nothing to generate from the tracked places". please guide me if I did something wrong. 

my models.jsonc is simple as in the sample: 
```jsonc
{
  "__className": "user_post", // <- The base class name of the object.
  "__path": "/lib/ztest/user_post", // <- override default path with a new one by adding '__path' key.
  "userId": 1,
  "id": 1, 
  "title": "Json To Dart Model", 
  "body": "Json to Dart advanced..."
}
```

**Comment by iamarnas** [comment]
@iqboladahamjonov Hi 👋

I'm sorry it does not work for you. The error message say att your default directory is empty and not `json` files detected, looks like you put your `json` files to the wrong directory. Your should put your all json files to the generated folder `./json_models`. And run build command.

```jsonc
{
    "_path": "/lib/models" // This path means where data models will be generated.
}
```

**Comment by iamarnas** [comment]
In my tests it work as expected and closing it due to not answer from the user. Reopen it if problem is still.
